<?php

declare(strict_types=1);

use BashBox\Bash;
use BashBox\BashOptions;
use BashBox\Exceptions\ExecutionLimitException;
use BashBox\Limits;

// Expected output was produced by GNU sed 4.9 in the C locale, running each script in bash with the same files.

const SED_USAGE = <<<'TXT'
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

  -n, --quiet, --silent
                 suppress automatic printing of pattern space
      --debug
                 annotate program execution
  -e script, --expression=script
                 add the script to the commands to be executed
  -f script-file, --file=script-file
                 add the contents of script-file to the commands to be executed
  --follow-symlinks
                 follow symlinks when processing in place
  -i[SUFFIX], --in-place[=SUFFIX]
                 edit files in place (makes backup if SUFFIX supplied)
  -l N, --line-length=N
                 specify the desired line-wrap length for the `l' command
  --posix
                 disable all GNU extensions.
  -E, -r, --regexp-extended
                 use extended regular expressions in the script
                 (for portability use POSIX -E).
  -s, --separate
                 consider files as separate rather than as a single,
                 continuous long stream.
      --sandbox
                 operate in sandbox mode (disable e/r/w commands).
  -u, --unbuffered
                 load minimal amounts of data from the input files and flush
                 the output buffers more often
  -z, --null-data
                 separate lines by NUL characters
      --help     display this help and exit
      --version  output version information and exit

If no -e, --expression, -f, or --file option is given, then the first
non-option argument is taken as the sed script to interpret.  All
remaining arguments are names of input files; if no input files are
specified, then the standard input is read.

GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.

TXT;

beforeEach(function (): void {
    $this->bash = new Bash(new BashOptions(cwd: '/home/user'));

    foreach (['a.txt' => "hello\nworld\n", 'partial' => 'no newline', 'b.txt' => "one\ntwo\nthree\n", 'n.txt' => implode("\n", range(1, 15))."\n", 'sub/x' => "x1\nx2\n"] as $path => $content) {
        $this->bash->writeFile('/home/user/'.$path, $content);
    }
});

$sed = function (string $script, string $stdout, string $stderr = '', int $exitCode = 0): void {
    $result = $this->bash->exec($script);

    expect($result->stdout)->toBe($stdout)
        ->and($result->stderr)->toBe($stderr)
        ->and($result->exitCode)->toBe($exitCode);
};

test('sed idioms, blocks, branches and file commands', $sed)->with([
    ["printf 'a\\nb\\nc\\n' | sed ':a;N;\$!ba;s/\\n/,/g'", "a,b,c\n"],
    ["printf 'x\\nstart\\n1\\n2\\nend\\ny\\n' | sed -n '/start/,/end/{/end/!p}'", "start\n1\n2\n"],
    ["printf '1\\n2\\n3\\n4\\n' | sed '\$!N;P;D'", "1\n2\n3\n4\n"],
    ["sed -e :a -e '\$q;N;11,\$D;ba' n.txt", "6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed '1!G;h;\$!d' b.txt", "three\ntwo\none\n"],
    ["printf 'a\\n\\n\\nb\\n\\nc\\n' | sed '/^\$/N;/\\n\$/D'", "a\n\nb\n\nc\n"],
    ["echo 1234567 | sed -e :a -e 's/\\(.*[0-9]\\)\\([0-9]\\{3\\}\\)/\\1,\\2/;ta'", "1,234,567\n"],
    ["printf 'abc\\n' | sed '/\\n/!G;s/\\(.\\)\\(.*\\n\\)/&\\2\\1/;//D;s/.//'", "cba\n"],
    ["sed -n '\$=' n.txt", "15\n"],
    ["sed '\$!d' n.txt", "15\n"],
    ["sed -n '2{p;q}' n.txt", "2\n"],
    ["sed = b.txt | sed 'N;s/\\n/\\t/'", "1\tone\n2\ttwo\n3\tthree\n"],
    ["printf 'a b\\n' | sed 's/ /\\n/' | sed -n l", "a\$\nb\$\n"],
    ["sed -n '/two/{=;p}' b.txt", "2\ntwo\n"],
    ["sed '2i\\\ninserted' b.txt", "one\ninserted\ntwo\nthree\n"],
    ["sed '/two/{x;p;x}' b.txt", "one\n\ntwo\nthree\n"],
    ["sed 'n;d' n.txt", "1\n3\n5\n7\n9\n11\n13\n15\n"],
    ["sed '\$!N;s/\\n/ /' n.txt", "1 2\n3 4\n5 6\n7 8\n9 10\n11 12\n13 14\n15\n"],
    ["sed -n 'h;n;G;p' b.txt", "two\none\n"],
    ["sed '/one/,/two/!d' b.txt", "one\ntwo\n"],
    ["sed '0~3d' n.txt", "1\n2\n4\n5\n7\n8\n10\n11\n13\n14\n"],
    ["sed -n '3,\${p;n;n;}' n.txt", "3\n6\n9\n12\n15\n"],
    ["sed '1~3{N;N;s/\\n/+/g}' n.txt", "1+2+3\n4+5+6\n7+8+9\n10+11+12\n13+14+15\n"],
    ["sed -n '/o/{/t/p}' b.txt", "two\n"],
    ["sed '2!{s/o/0/}' b.txt", "0ne\ntwo\nthree\n"],
    ["sed -n '1,2{p;p}' b.txt", "one\none\ntwo\ntwo\n"],
    ["sed '{{{p}}}' b.txt", "one\none\ntwo\ntwo\nthree\nthree\n"],
    ["sed -n '/one/{n;p}' b.txt", "two\n"],
    ["sed '1{h;d};G' b.txt", "two\none\nthree\none\n"],
    ["sed -e '/two/{' -e 's/t/T/' -e '}' b.txt", "one\nTwo\nthree\n"],
    ["sed '/two/ !{ s/e/E/ ; }' b.txt", "onE\ntwo\nthrEe\n"],
    ["sed '{p};p' b.txt", "one\none\none\ntwo\ntwo\ntwo\nthree\nthree\nthree\n"],
    ["sed '{p}p' b.txt", '', "sed: -e expression #1, char 4: extra characters after command\n", 1],
    ["sed '{p' b.txt", '', "sed: -e expression #1, char 0: unmatched `{'\n", 1],
    ["sed 'p}' b.txt", '', "sed: -e expression #1, char 2: unexpected `}'\n", 1],
    ["sed '1}' b.txt", '', "sed: -e expression #1, char 2: unexpected `}'\n", 1],
    ["sed '{p};}' b.txt", '', "sed: -e expression #1, char 5: unexpected `}'\n", 1],
    ["sed -n '{p}#x' b.txt", "one\ntwo\nthree\n"],
    ["sed -n '/x/{p' b.txt", '', "sed: -e expression #1, char 0: unmatched `{'\n", 1],
    ["sed -n '1{2{p}}' b.txt", ''],
    ["sed ':a;s/o/0/;ta' b.txt", "0ne\ntw0\nthree\n"],
    ["sed ':a\ns/o/0/\nt a' b.txt", "0ne\ntw0\nthree\n"],
    ["sed -n ':top;/e/{s/e/E/;b top};p' b.txt", "onE\ntwo\nthrEE\n"],
    ["sed 's/o/0/;T;s/\$/!/' b.txt", "0ne!\ntw0!\nthree\n"],
    ["sed 's/o/0/;Tend;s/\$/!/;:end' b.txt", "0ne!\ntw0!\nthree\n"],
    ["sed 'b;s/o/0/' b.txt", "one\ntwo\nthree\n"],
    ["sed 'bx;s/o/0/;:x' b.txt", "one\ntwo\nthree\n"],
    ["sed 'b x ; s/o/0/;: x' b.txt", "one\ntwo\nthree\n"],
    ["sed -n 's/x/y/;t;p' b.txt", "one\ntwo\nthree\n"],
    ["sed 'b foo' b.txt", '', "sed: can't find label for jump to `foo'\n", 4],
    ["sed ':' b.txt", '', "sed: -e expression #1, char 1: \":\" lacks a label\n", 1],
    ["sed '1:a' b.txt", '', "sed: -e expression #1, char 2: : doesn't want any addresses\n", 1],
    ["sed ':a;:a;s/o/0/;ta' b.txt", "0ne\ntw0\nthree\n"],
    ["sed -e 's/o/0/' -e 'N;tx' -e 's/^/-/;:x' b.txt", "-0ne\ntwo\nthree\n"],
    ["sed 's/t/T/;N;s/n/N/;t;s/^/>/' b.txt", "oNe\ntwo\nThree\n"],
    ["sed -n '/two/b skip;p;:skip' b.txt", "one\nthree\n"],
    ["sed 'b end;s/a/b/;:end}' b.txt", '', "sed: -e expression #1, char 18: unexpected `}'\n", 1],
    ["sed '{:a;s/o/0/;ta}' b.txt", "0ne\ntw0\nthree\n"],
    ["sed ':a#c\ns/o/0/;ta' b.txt", "0ne\ntw0\nthree\n"],
    ['sed 3q n.txt', "1\n2\n3\n"],
    ["sed -n '3{p;q}' n.txt", "3\n"],
    ["sed '3Q' n.txt", "1\n2\n"],
    ["sed 'q5' b.txt; echo \$?", "one\n5\n"],
    ["sed 'Q 7' b.txt; echo \$?", "7\n"],
    ["sed '2q300' b.txt; echo \$?", "one\ntwo\n44\n"],
    ["printf 'a' | sed q", "a\n"],
    ["printf 'a' | sed 'a x' | tr '\\000' @", "a\nx\n"],
    ["sed '1,2q' b.txt", '', "sed: -e expression #1, char 4: command only uses one address\n", 1],
    ["sed '1a foo\n1q' b.txt", "one\nfoo\n"],
    ["sed '1i foo\n1Q' b.txt", "foo\n"],
    ["sed '1r a.txt' b.txt", "one\nhello\nworld\ntwo\nthree\n"],
    ["sed 'r a.txt' partial", "no newline\nhello\nworld\n"],
    ["sed '\$r partial' b.txt", "one\ntwo\nthree\nno newline"],
    ["sed '0r a.txt' b.txt", "hello\nworld\none\ntwo\nthree\n"],
    ["sed '0r nope' b.txt", "one\ntwo\nthree\n"],
    ["sed 'r nope' b.txt", "one\ntwo\nthree\n"],
    ["sed '2r sub' b.txt", "one\ntwo\n", "sed: read error on sub: Is a directory\n", 4],
    ["sed 'R a.txt' b.txt", "one\nhello\ntwo\nworld\nthree\n"],
    ["sed 'R partial' b.txt", "one\nno newlinetwo\nthree\n"],
    ["sed 'R nope' b.txt", "one\ntwo\nthree\n"],
    ["sed -e 'R a.txt' -e 'R a.txt' n.txt", "1\nhello\nworld\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed '1R a.txt\n1a X\n1r partial' b.txt", "one\nhello\nX\nno newlinetwo\nthree\n"],
    ["sed -n 'w out' b.txt; cat out", "one\ntwo\nthree\n"],
    ["sed -n '/t/w out' b.txt partial; cat out", "two\nthree\n"],
    ["sed -n '2W out' b.txt; cat out", "two\n"],
    ["sed -n 'N;W out' b.txt; cat out", "one\n"],
    ["sed 'w /dev/stdout' b.txt", "one\none\ntwo\ntwo\nthree\nthree\n"],
    ["sed -n 'w /dev/stderr' b.txt", '', "one\ntwo\nthree\n"],
    ["sed 's/o/0/w out' b.txt; cat out", "0ne\ntw0\nthree\n0ne\ntw0\n"],
    ["sed 's/o/0/gpw out' b.txt; cat out", "0ne\n0ne\ntw0\ntw0\nthree\n0ne\ntw0\n"],
    ["sed 'w out;p' b.txt; ls; cat 'out;p'", "one\ntwo\nthree\na.txt\nb.txt\nn.txt\nout;p\npartial\nsub\none\ntwo\nthree\n"],
    ["sed -n 'w out' partial; tr '\\000' @ < out", 'no newline'],
    ["sed -n 'w out\nw out' b.txt; cat out", "one\none\ntwo\ntwo\nthree\nthree\n"],
    ["sed 'w nodir/f' b.txt", '', "sed: couldn't open file nodir/f: No such file or directory\n", 4],
    ["sed 'w sub' b.txt", '', "sed: couldn't open file sub: Is a directory\n", 4],
    ["sed 'r' b.txt", '', "sed: -e expression #1, char 1: missing filename in r/R/w/W commands\n", 1],
    ["sed 'w' b.txt", '', "sed: -e expression #1, char 1: missing filename in r/R/w/W commands\n", 1],
    ["sed 'w ' b.txt", '', "sed: -e expression #1, char 2: missing filename in r/R/w/W commands\n", 1],
    ["sed --sandbox 'w x' b.txt", '', "sed: -e expression #1, char 1: e/r/w commands disabled in sandbox mode\n", 1],
    ["sed --sandbox 'r x' b.txt", '', "sed: -e expression #1, char 1: e/r/w commands disabled in sandbox mode\n", 1],
    ["sed --sandbox 'e echo' b.txt", '', "sed: -e expression #1, char 1: e/r/w commands disabled in sandbox mode\n", 1],
    ["sed --sandbox 's/x/y/e' b.txt", '', "sed: -e expression #1, char 7: e/r/w commands disabled in sandbox mode\n", 1],
    ['sed --sandbox p b.txt', "one\none\ntwo\ntwo\nthree\nthree\n"],
    ["echo hi | sed 'r /dev/stdin' b.txt", "one\nhi\ntwo\nthree\n"],
    ["echo hi | sed '1R /dev/stdin' b.txt", "one\nhi\ntwo\nthree\n"],
    ["sed 'w a.txt' b.txt; cat a.txt", "one\ntwo\nthree\none\ntwo\nthree\n"],
    ["echo 'echo hello' | sed e", "hello\n"],
    ["printf 'echo hello' | sed e", "hello\n"],
    ["echo x | sed 'e echo pre'", "pre\nx\n"],
    ["echo x | sed '1e echo pre\na post'", "pre\nx\npost\n"],
    ["echo 'echo a; echo b' | sed e", "a\nb\n"],
    ["echo 'abc' | sed 's/.*/echo &|tr a-z A-Z/e'", "ABC\n"],
    ["echo 'abc' | sed -n 's/.*/echo X/ep'", "X\n"],
    ["echo 'abc' | sed -n 's/.*/echo X/pe'", "echo X\n"],
    ["echo 'printf q' | sed 'e'", "q\n"],
    ["echo 'cat nope' | sed 'e'", "\n", "cat: nope: No such file or directory\n"],
    ["printf 'a\\tb\\001\\x80\\\\\\n' | sed -n 'l;l 5;l 0;l1'", "a\\tb\\001\\200\\\\\$\na\\tb\\\n\\001\\\n\\200\\\n\\\\\$\na\\tb\\001\\200\\\\\$\n\\\na\\\n\\t\\\nb\\\n\\001\\\n\\200\\\n\\\\\$\n"],
    ["printf '%s\\n' aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa | sed -n l", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\\naaaaaaaaaaaaaaaaaaa\$\n"],
    ["printf '%s\\n' aaaaaaaaaa | sed -l 5 -n l", "aaaa\\\naaaa\\\naa\$\n"],
    ["printf '%s\\n' aaaaaaaaaa | sed -l5 -n 'l;l 4'", "aaaa\\\naaaa\\\naa\$\naaa\\\naaa\\\naaa\\\na\$\n"],
    ["printf '%s\\n' aaaaaaaaaa | sed --line-length=3 -n l", "aa\\\naa\\\naa\\\naa\\\naa\$\n"],
    ["printf '%s\\n' aaaaaaaaaa | COLS=5 sed -n l", "aaa\\\naaa\\\naaa\\\na\$\n"],
    ["printf '%s\\n' aaaaaaaaaa | COLS=1 sed -n l", "aaaaaaaaaa\$\n"],
    ["printf 'a\\x7f\\x1b\\b\\f\\r\\v\\x07b\\n' | sed -n l", "a\\177\\033\\b\\f\\r\\v\\ab\$\n"],
    ["printf 'a\\n' | sed 'G;l;d'", "a\\n\$\n"],
    ["printf 'ab' | sed 'l'", "ab\$\nab"],
    ["printf 'a\\nb' | sed -n 'l'", "a\$\nb\$\n"],
    ["sed -n 'l 3x' b.txt", '', "sed: -e expression #1, char 4: extra characters after command\n", 1],
    ['sed F b.txt', "b.txt\none\nb.txt\ntwo\nb.txt\nthree\n"],
    ["sed -n '\$F' b.txt a.txt", "a.txt\n"],
    ["sed -s -n '\$F' b.txt a.txt", "b.txt\na.txt\n"],
    ['cat b.txt | sed 1F', "-\none\ntwo\nthree\n"],
    ["sed 'z;s/^\$/E/' b.txt", "E\nE\nE\n"],
    ["sed -n '/t/=' b.txt", "2\n3\n"],
    ["printf 'a' | sed =", "1\na"],
    ["printf 'a' | sed -n 'p;='", "a\n1\n"],
    ['echo x | sed L', '', "sed: INTERNAL ERROR: Bad cmd L\n", 4],
    ["printf '' | sed L", ''],
    ["sed 's/o/0/w /dev/stdout' b.txt", "0ne\n0ne\ntw0\ntw0\nthree\n"],
    ["sed -n 'W /dev/stderr' b.txt", '', "one\ntwo\nthree\n"],
    ["sed -s -n 'F;w out' a.txt b.txt; cat out", "a.txt\na.txt\nb.txt\nb.txt\nb.txt\nhello\nworld\none\ntwo\nthree\n"],
    ["sed -n 'R b.txt' -e '1R b.txt' a.txt", "one\n", "sed: can't read R b.txt: No such file or directory\n", 2],
    ["sed -i 'R a.txt' b.txt n.txt; cat b.txt; head -3 n.txt", "one\nhello\ntwo\nworld\nthree\n1\nhello\n2\n"],
    ["sed -i -n 'w out' b.txt a.txt; cat out b.txt", "one\ntwo\nthree\nhello\nworld\n"],
    ["printf 'a\\0b' | sed -z '\$s/b/B/' | tr '\\000' @", 'a@B'],
    ["printf 'a\\0b\\0' | sed -z -n 'l 3' | tr '\\000' @", 'a$@b$@'],
    ["printf 'echo x\\0' | sed -z 'e' | tr '\\000' @", "x\n@"],
    ["printf 'a\\nb\\0c\\0' | sed -z 's/^b/X/M' | tr '\\000' @", "a\nb@c@"],
    ["printf 'a\\0b\\0' | sed -z 'N;s/a.b/X/' | tr '\\000' @", 'X@'],
    ["printf 'a\\0b\\0' | sed -z 'N;P;D' | tr '\\000' @", 'a@b@'],
    ["printf 'a\\0b\\0' | sed -z '=' | tr '\\000' @", '1@a@2@b@'],
    ["printf 'a\\0b\\0' | sed -z 'F;i X' | tr '\\000' @", '-@X@a@-@X@b@'],
    ["printf 'a\\0b\\0' | sed -z 'c X' | tr '\\000' @", 'X@X@'],
    ["printf 'a\\0b' | sed -z 'p' | tr '\\000' @", 'a@a@b@b'],
    ["printf 'a\\nb\\n' | sed -z 's/\\n/,/g'", 'a,b,'],
    ["printf 'a\\nb\\n' | sed -z 'G' | tr '\\000' @", "a\nb\n@@"],
    ["sed -n '\$p' - b.txt < a.txt", "three\n"],
    ["sed -n '1~2{N;s/\\n/=/p}' n.txt", "1=2\n3=4\n5=6\n7=8\n9=10\n11=12\n13=14\n"],
    ["sed '2,4{2d;s/^/x/}' n.txt", "1\nx3\nx4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '/3/{:a;N;/6/!ba;s/\\n/ /g;p}' n.txt", "3 4 5 6\n"],
    ["sed '/^1\$/,/^3\$/{//!d}' n.txt", "1\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '/1/{//p}' n.txt", "1\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n 's/1/X/;//p' n.txt", "X1\n"],
    ["sed '\$!{h;d};x;G' b.txt", "two\nthree\n"],
    ["sed -e '1{x;s/^/A/;x}' -e 'G' b.txt", "one\nA\ntwo\nA\nthree\nA\n"],
    ["sed 'N;N;N;N;D' n.txt", "4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed '5!d;=' n.txt", "5\n5\n"],
    ["sed '2,+2{=;d}' n.txt", "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '12,\$!{\$!p}' n.txt", "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n"],
    ["sed '/4/,\${/8/q;s/\$/!/}' n.txt", "1\n2\n3\n4!\n5!\n6!\n7!\n8\n"],
    ["sed -n '\$!N;/\\(.*\\)\\n\\1\$/!P;D' n.txt", "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["printf 'a\\na\\nb\\nb\\nb\\nc\\n' | sed '\$!N;/^\\(.*\\)\\n\\1\$/!P;D'", "a\nb\nc\n"],
    ["printf 'line one\\nline two\\n' | sed -E 's/(\\w+) (\\w+)/\\U\\2\\E-\\1/'", "ONE-line\nTWO-line\n"],
    ["printf 'abc\\n' | sed -E 's/(.)(.)(.)/\\3\\2\\1/'", "cba\n"],
    ["printf 'a  b   c\\n' | sed 's/  */ /g'", "a b c\n"],
    ["printf 'a\\tb\\n' | sed -E 's/\\s+/_/'", "a_b\n"],
    ["printf '123abc\\n' | sed -E 's/[0-9]+/(&)/'", "(123)abc\n"],
    ["printf 'x\\n' | sed 's/x/a\\\nb/;P;D'", "a\nb\n"],
    ["printf 'hello\\n' | sed 's/./(&)/3'", "he(l)lo\n"],
    ["printf 'foo\\nbar\\n' | sed -n '/foo/{n;s/bar/BAR/p}'", "BAR\n"],
    ["printf 'foo\\n' | sed 'y/fo/of/;s/o/0/2'", "off\n"],
    ["printf 'a\\n' | sed -n 'x;p;x;p'", "\na\n"],
    ["printf 'a\\n' | sed 'H;H;x'", "\na\na\n"],
    ["printf 'a\\n' | sed '1!G;\$!h'", "a\n"],
    ["seq 10 | sed -n '0~3p'", "3\n6\n9\n"],
    ["seq 10 | sed '3,~4d'", "1\n2\n5\n6\n7\n8\n9\n10\n"],
    ["seq 10 | sed -n '/5/,+0p;/7/,~0p'", "5\n7\n"],
    ["seq 5 | sed -n '2{p;n;p;n;p}'", "2\n3\n4\n"],
    ["seq 5 | sed 'N;N;s/\\n/+/g'", "1+2+3\n4\n5\n"],
    ["seq 6 | sed -n 'h;n;G;p'", "2\n1\n4\n3\n6\n5\n"],
    ["seq 3 | sed -s '1i\\\nhead' - b.txt", "head\n1\n2\n3\nhead\none\ntwo\nthree\n"],
    ["seq 3 | sed G | sed -n '/^\$/='", "2\n4\n6\n"],
]);

test('sed options and input files', $sed)->with([
    ['sed -n p b.txt', "one\ntwo\nthree\n"],
    ['sed --quiet p b.txt', "one\ntwo\nthree\n"],
    ['sed --silent -e p b.txt', "one\ntwo\nthree\n"],
    ['sed --expression=p b.txt', "one\none\ntwo\ntwo\nthree\nthree\n"],
    ['sed --expression p b.txt', "one\none\ntwo\ntwo\nthree\nthree\n"],
    ['sed --expr=p b.txt', "one\none\ntwo\ntwo\nthree\nthree\n"],
    ['sed --in-place=.bak s/o/0/ b.txt; cat b.txt b.txt.bak', "0ne\ntw0\nthree\none\ntwo\nthree\n"],
    ['sed --in-place s/o/0/ b.txt; cat b.txt; ls', "0ne\ntw0\nthree\na.txt\nb.txt\nn.txt\npartial\nsub\n"],
    ['sed -i -e s/o/0/ b.txt a.txt; cat b.txt a.txt', "0ne\ntw0\nthree\nhell0\nw0rld\n"],
    ['sed -ibak s/o/0/ b.txt; cat b.txt bbak 2>&1; ls', "0ne\ntw0\nthree\ncat: bbak: No such file or directory\na.txt\nb.txt\nb.txtbak\nn.txt\npartial\nsub\n"],
    ["sed -i'bk_*' s/o/0/ b.txt; ls; cat bk_b.txt", "a.txt\nb.txt\nbk_b.txt\nn.txt\npartial\nsub\none\ntwo\nthree\n"],
    ["sed -i'*.old' s/o/0/ sub/x; ls sub", "x\nx.old\n"],
    ['sed -n -i p b.txt; cat b.txt', "one\ntwo\nthree\n"],
    ['sed -i 2q n.txt; cat n.txt', "1\n2\n"],
    ["sed -i -s 'q' b.txt a.txt; cat b.txt a.txt", "one\nhello\nworld\n"],
    ["sed -i '\$a end' b.txt partial; cat b.txt partial", "one\ntwo\nthree\nend\nno newline\nend\n"],
    ["sed -i 'F;=' b.txt; cat b.txt", "b.txt\n1\none\nb.txt\n2\ntwo\nb.txt\n3\nthree\n"],
    ["sed -i '1w /dev/stdout' b.txt; cat b.txt", "one\none\ntwo\nthree\n"],
    ['sed -i p -', '', "sed: can't read -: No such file or directory\n", 2],
    ['sed -i p sub', '', "sed: couldn't edit sub: not a regular file\n", 4],
    ['sed -i p nope b.txt; cat b.txt', "one\none\ntwo\ntwo\nthree\nthree\n", "sed: can't read nope: No such file or directory\n"],
    ['echo x | sed -s p - b.txt', "x\nx\none\none\ntwo\ntwo\nthree\nthree\n"],
    ["sed -s '1d' a.txt b.txt", "world\ntwo\nthree\n"],
    ["sed -s 'H;\$!d;x' a.txt b.txt", "\nhello\nworld\n\none\ntwo\nthree\n"],
    ["sed '1d' a.txt b.txt", "world\none\ntwo\nthree\n"],
    ["sed -s '0,/o/d' a.txt b.txt", "world\ntwo\nthree\n"],
    ["sed -s -n 'R partial' a.txt b.txt", 'no newlineno newline'],
    ["sed -s -n '1R a.txt' b.txt n.txt", "hello\nhello\n"],
    ["sed -sn '\$p' a.txt b.txt", "world\nthree\n"],
    ["sed -ns '\$p' a.txt b.txt", "world\nthree\n"],
    ["sed -nE '/(o)\\1/p' a.txt", ''],
    ["sed -rn '/l{2}/p' a.txt", "hello\n"],
    ["sed -En -e '/l{2}/p' a.txt", "hello\n"],
    ['sed -f script b.txt', '', "sed: couldn't open file script: No such file or directory\n", 4],
    ["printf 's/o/0/\\np\\n' > script; sed -f script b.txt", "0ne\n0ne\ntw0\ntw0\nthree\nthree\n"],
    ["printf 's/o/0/\\np\\n' > script; sed -n -f script -e = b.txt", "0ne\n1\ntw0\n2\nthree\n3\n"],
    ["printf '#n\\np\\n' > script; sed -f script b.txt", "one\ntwo\nthree\n"],
    ["printf '#n\\np\\n' > script; sed -e p -f script b.txt", "one\none\none\ntwo\ntwo\ntwo\nthree\nthree\nthree\n"],
    ["printf 's/o/0\\np\\n' > script; sed -f script b.txt", '', "sed: file script line 1: unterminated `s' command\n", 1],
    ["printf 'p\\n{\\n' > script; sed -f script b.txt", '', "sed: file script line 2: unmatched `{'\n", 1],
    ["printf 'p\\n\\nbfoo\\n' > script; sed -f script b.txt", '', "sed: can't find label for jump to `foo'\n", 4],
    ["printf 'p\\n' | sed -f - b.txt", "one\none\ntwo\ntwo\nthree\nthree\n"],
    ["printf 'a\\\\\\n' > script; sed -f script -e foo b.txt", '', "sed: -e expression #1, char 1: unknown command: `f'\n", 1],
    ["printf '1d' | sed -f /dev/stdin b.txt", "two\nthree\n"],
    ['sed -fscript b.txt', '', "sed: couldn't open file script: No such file or directory\n", 4],
    ['sed -f nope b.txt', '', "sed: couldn't open file nope: No such file or directory\n", 4],
    ['sed -f sub b.txt', "one\ntwo\nthree\n"],
    ["sed -z 's/^/>/' b.txt", ">one\ntwo\nthree\n"],
    ["printf 'a\\0b\\0' | sed -z 's/^/>/;a foo' | tr '\\000' @", ">a@foo\n>b@foo\n"],
    ["printf 'a\\0b\\0' | sed -z 'N;l;=;i foo' | tr '\\000' @", 'a\\000b$@2@foo@a@b@'],
    ["printf 'a\\0b\\0c' | sed -z '\$!d' | tr '\\000' @", 'c'],
    ["printf 'a\\nb\\0c\\nd\\0' | sed -z 'N;P;D' | tr '\\000' @", "a\nb@c\nd@"],
    ["printf 'a\\0b\\0' | sed --null-data 'G;H' | tr '\\000' @", 'a@@b@@a@@'],
    ["printf 'a\\0b\\0' | sed -z 'y/a/\\x00/' | tr '\\000' @", '@@b@'],
    ['sed -u p b.txt', "one\none\ntwo\ntwo\nthree\nthree\n"],
    ['sed -b p b.txt', "one\none\ntwo\ntwo\nthree\nthree\n"],
    ['sed --follow-symlinks p b.txt', "one\none\ntwo\ntwo\nthree\nthree\n"],
    ['sed --unbuffered --binary --separate p b.txt', "one\none\ntwo\ntwo\nthree\nthree\n"],
    ['sed -ek', '', "sed: -e expression #1, char 1: unknown command: `k'\n", 1],
    ['sed --version | head -1', "sed (GNU sed) 4.9\n"],
    ['sed --help | head -3', "Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...\n\n  -n, --quiet, --silent\n"],
    ['sed -n', '', "Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...\n\n  -n, --quiet, --silent\n                 suppress automatic printing of pattern space\n      --debug\n                 annotate program execution\n  -e script, --expression=script\n                 add the script to the commands to be executed\n  -f script-file, --file=script-file\n                 add the contents of script-file to the commands to be executed\n  --follow-symlinks\n                 follow symlinks when processing in place\n  -i[SUFFIX], --in-place[=SUFFIX]\n                 edit files in place (makes backup if SUFFIX supplied)\n  -l N, --line-length=N\n                 specify the desired line-wrap length for the `l' command\n  --posix\n                 disable all GNU extensions.\n  -E, -r, --regexp-extended\n                 use extended regular expressions in the script\n                 (for portability use POSIX -E).\n  -s, --separate\n                 consider files as separate rather than as a single,\n                 continuous long stream.\n      --sandbox\n                 operate in sandbox mode (disable e/r/w commands).\n  -u, --unbuffered\n                 load minimal amounts of data from the input files and flush\n                 the output buffers more often\n  -z, --null-data\n                 separate lines by NUL characters\n      --help     display this help and exit\n      --version  output version information and exit\n\nIf no -e, --expression, -f, or --file option is given, then the first\nnon-option argument is taken as the sed script to interpret.  All\nremaining arguments are names of input files; if no input files are\nspecified, then the standard input is read.\n\nGNU sed home page: <https://www.gnu.org/software/sed/>.\nGeneral help using GNU software: <https://www.gnu.org/gethelp/>.\n", 1],
    ['sed -- -n b.txt', '', "sed: -e expression #1, char 1: unknown command: `-'\n", 1],
    ['sed p -- -n', '', "sed: can't read -n: No such file or directory\n", 2],
    ['sed b.txt -n p', '', "sed: can't find label for jump to `.txt'\n", 4],
    ['sed -n p b.txt -s a.txt', "one\ntwo\nthree\nhello\nworld\n"],
    ["sed -e p -e '' b.txt", "one\none\ntwo\ntwo\nthree\nthree\n"],
    ["sed -e 'a\\' -e foo b.txt", "one\nfoo\ntwo\nfoo\nthree\nfoo\n"],
    ["sed -e 'a foo\\' -e bar b.txt", "one\nfoo\nbar\ntwo\nfoo\nbar\nthree\nfoo\nbar\n"],
    ["sed -e 'a\\' b.txt", "one\ntwo\nthree\n"],
    ["sed -e 'i\\' -e '' b.txt", "\none\n\ntwo\n\nthree\n"],
    ["sed -e '1{' -e p b.txt", '', "sed: -e expression #1, char 0: unmatched `{'\n", 1],
    ["sed -e p -e 's//x/' b.txt", "one\n", "sed: -e expression #2, char 0: no previous regular expression\n", 1],
    ["sed -e 'a\\' -e 'foo\\' -e 'bar' b.txt", "one\nfoo\nbar\ntwo\nfoo\nbar\nthree\nfoo\nbar\n"],
    ["sed -e 'a\\' -e '' b.txt", "one\n\ntwo\n\nthree\n\n"],
    ["sed -e 's/a/b/' -e 's/b' b.txt", '', "sed: -e expression #2, char 3: unterminated `s' command\n", 1],
    ["sed -e 's/x/y/' -e 'b' -e 'p' b.txt", "one\ntwo\nthree\n"],
    ["sed -n -e '/one/{' -e 'p' -e '}' b.txt", "one\n"],
    ["sed -n -e '1{p' -e '}' b.txt", "one\n"],
    ["sed -e 'p' nope b.txt; echo \$?", "one\none\ntwo\ntwo\nthree\nthree\n2\n", "sed: can't read nope: No such file or directory\n"],
    ["sed -n 'q' nope b.txt; echo \$?", "2\n", "sed: can't read nope: No such file or directory\n"],
    ["sed -n 'q' b.txt nope; echo \$?", "0\n"],
    ["sed -n '\$p' b.txt nope; echo \$?", "three\n2\n", "sed: can't read nope: No such file or directory\n"],
    ["sed -n '\$p' b.txt nope a.txt; echo \$?", "world\n2\n", "sed: can't read nope: No such file or directory\n"],
    ["printf '' > empty; sed -n '\$p' b.txt empty", "three\n"],
    ["printf '' > empty; sed -n '\$=' empty b.txt empty", "3\n"],
    ['sed p sub', '', "sed: read error on sub: Is a directory\n", 4],
    ["sed 'q5' nope b.txt; echo \$?", "one\n2\n", "sed: can't read nope: No such file or directory\n"],
]);

test('sed regular expressions, escapes, text and addresses', $sed)->with([
    ["echo 'a.b' | sed 's/[[.-.]]/X/;s/[[=b=]]/Y/'", "a.Y\n"],
    ["echo 'a.b' | sed 's/[[.period.]]/X/'", '', "sed: -e expression #1, char 17: Invalid collation character\n", 1],
    ["echo 'abc' | sed 's/[[=bc=]]/X/'", '', "sed: -e expression #1, char 13: Invalid collation character\n", 1],
    ["echo 'a]b' | sed 's/[[.].]]/X/'", "aXb\n"],
    ["echo 'a-b' | sed 's/[a[.-.]z]/X/g'", "XXb\n"],
    ["echo 'a^b' | sed 's/[[.^.]]/X/g'", "aXb\n"],
    ["echo 'a\\\\b' | sed 's/[[.\\\\.]]/X/g'", '', "sed: -e expression #1, char 14: Invalid collation character\n", 1],
    ["printf 'a\\nb\\n' | sed 'N;s/a.b/X/'", "X\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/a[^x]b/X/'", "X\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/a[^x]b/X/M'", "a\nb\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/a.b/X/M'", "a\nb\n"],
    ["echo a | sed 'G;s/a\$/X/'", "a\n\n"],
    ["echo a | sed 'G;s/a\$/X/M'", "X\n\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/^/>/g'", ">a\nb\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/\$/</Mg'", "a<\nb<\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/\\`/>/Mg;s/\\'\"'\"'/</Mg'", ">a\nb<\n"],
    ["echo abcd | sed -E 's/(a|ab)(c|bcd)/[\\1,\\2]/'", "[a,bcd]\n"],
    ["echo aaa | sed -E 's/a{,2}/X/'", "Xa\n"],
    ["echo 'a{' | sed -E 's/a{/X/'", '', "sed: -e expression #1, char 7: Unmatched \\{\n", 1],
    ["echo 'a{1' | sed -E 's/a{1/X/'", '', "sed: -e expression #1, char 8: Unmatched \\{\n", 1],
    ["echo 'a{' | sed 's/a\\{/X/'", '', "sed: -e expression #1, char 8: Unmatched \\{\n", 1],
    ["echo 'a{x}' | sed -E 's/a{x}/X/'", '', "sed: -e expression #1, char 9: Invalid content of \\{\\}\n", 1],
    ["echo 'ab' | sed -E 's/a|*b/X/g'", '', "sed: -e expression #1, char 10: Invalid preceding regular expression\n", 1],
    ["echo 'a+b' | sed 's/a+b/X/'", "X\n"],
    ["echo 'aab' | sed 's/a\\+b/X/'", "X\n"],
    ["echo 'ab' | sed -E 's/()b/X\\1/'", "aX\n"],
    ["echo 'abab' | sed -E 's/(ab)\\1/X/'", "X\n"],
    ["echo 'abab' | sed 's/\\(ab\\)\\1/X/'", "X\n"],
    ["echo 'a b' | sed 's/\\s/_/;s/\\S/X/'", "X_b\n"],
    ["echo 'a_b c' | sed 's/\\w*/X/;s/\\W/Y/'", "XYc\n"],
    ["echo 'abc abc' | sed 's/\\babc\\b/X/2;s/\\Bb\\B/Y/'", "aYc X\n"],
    ["echo 'abc' | sed 's/\\(a\\|b\\)*/X/'", "Xc\n"],
    ["echo 'abc' | sed -n '/^a.c\$/p'", "abc\n"],
    ["echo 'a*c' | sed 's/a\\*c/X/'", "X\n"],
    ["echo 'a.c' | sed -E 's/a\\.c/X/'", "X\n"],
    ["echo 'TAB' | sed 's/tab/x/I'", "x\n"],
    ["echo 'TAB' | sed '/tab/Id'", ''],
    ["echo 'TAB' | sed '/tab/I,/x/d'", ''],
    ["echo 'TAB' | sed '/tab/ I d'", ''],
    ["echo 'abc' | sed 's/b*/X/g'", "XaXcX\n"],
    ["echo 'baaac' | sed 's/a*/x/g'", "xbxcx\n"],
    ["echo 'abc' | sed 's/b*/X/2'", "aXc\n"],
    ["echo 'abc' | sed 's/x*/-/3g'", "ab-c-\n"],
    ["echo 'hello' | sed 's/l/L/2g'", "helLo\n"],
    ["echo 'hello' | sed 's/l*/X/2'", "hXello\n"],
    ["echo 'hello' | sed -n 's/z/Z/p'", ''],
    ["echo 'aaa' | sed 's/a/b/4'", "aaa\n"],
    ["echo 'a' | sed 's/a/\\n/' | sed -n l", "\$\n\$\n"],
    ["echo 'a.b' | sed 's/\\x2e/X/'", "X.b\n"],
    ["echo 'a*b' | sed 's/a\\d042/X/'", "X*b\n"],
    ["echo 'a&b' | sed 's/&/\\x26\\x26/'", "a&&b\n"],
    ["echo 'ab' | sed 's/a/\\x5c/'", "\\b\n"],
    ["echo 'ab' | sed 's/a/[\\o101\\d066\\x43]/'", "[ABC]b\n"],
    ["echo 'ab' | sed 's/a/\\cA\\ca\\c[/' | sed -n l", "\\001\\001\\033b\$\n"],
    ["echo 'ab' | sed 's/a/\\c\\\\/' | sed -n l", "\\034b\$\n"],
    ["echo 'ab' | sed 's/a/\\c\\d/'", '', "sed: -e expression #1, char 9: recursive escaping after \\c not allowed\n", 1],
    ["echo 'ab' | sed 's/a/\\c/'", "\\b\n"],
    ["echo 'ab' | sed 's/b\\c/X/'", '', "sed: -e expression #1, char 8: Trailing backslash\n", 1],
    ["echo 'ab' | sed 's/a/\\a\\f\\v\\r/' | sed -n l", "\\a\\f\\v\\rb\$\n"],
    ["echo 'ab' | sed 's/a/\\x/;s/b/\\d/'", "xd\n"],
    ["echo 'ab' | sed 's/a/\\xg\\o9/'", "xgo9b\n"],
    ["echo 'ab' | sed 's/a/\\x41\\x4/'", "A\x04b\n"],
    ["echo 'ab' | sed 's/a/\\d300\\o777/' | sed -n l", ",\\377b\$\n"],
    ["printf 'a\\tb\\n' | sed 's/[\\t]/T/'", "aTb\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/[\\n]/N/'", "aNb\n"],
    ["echo 'a\\nb' | sed 's/[\\\\n]/X/g'", "aXXb\n"],
    ["echo 'ab' | sed 'y/ab/\\x41\\n/' | sed -n l", "A\$\n\$\n"],
    ["echo 'abc' | sed 'y/abc/\\t\\n\\\\/' | sed -n l", "\\t\$\n\\\\\$\n"],
    ["echo 'a/b' | sed 'y,/,|,'", "a|b\n"],
    ["echo 'a,b' | sed 'y,\\,,|,'", "a|b\n"],
    ["echo 'aab' | sed 'y/aa/xy/'", "yyb\n"],
    ["echo 'ab' | sed 'y/a/b/;y/b/c/'", "cc\n"],
    ["echo 'ab' | sed 'y/a/bc/'", '', "sed: -e expression #1, char 7: strings for `y' command are different lengths\n", 1],
    ["echo 'ab' | sed 'y/a/b/x'", '', "sed: -e expression #1, char 7: extra characters after command\n", 1],
    ["echo 'ab' | sed 'y/a/b/;p'", "bb\nbb\n"],
    ["echo 'ab' | sed 'y/a/b'", '', "sed: -e expression #1, char 5: unterminated `y' command\n", 1],
    ["echo 'a&b' | sed 'y&\\&&x&'", "axb\n"],
    ["echo 'x' | sed 'a foo\\tbar'", "x\nfoo\tbar\n"],
    ["echo 'x' | sed 'a foo\\tbar\\'", "x\nfoo\\tbar\n"],
    ["echo 'x' | sed 'a\\tfoo'", "x\ntfoo\n"],
    ["echo 'x' | sed 'a\\  foo'", "x\n  foo\n"],
    ["echo 'x' | sed 'a\\\n  foo\\\n  bar'", "x\n  foo\n  bar\n"],
    ["echo 'x' | sed 'a\\\nfoo\\\\'", "x\nfoo\\\n"],
    ["echo 'x' | sed 'a   foo  '", "x\nfoo  \n"],
    ["echo 'x' | sed 'i\\'", "x\n"],
    ["echo 'x' | sed 'c\\'", ''],
    ["echo 'x' | sed 'a\\x41\\d066'", "x\nx41B\n"],
    ["printf 'a\\nb\\n' | sed '1{a X\n}'", "a\nX\nb\n"],
    ["printf 'a\\nb\\n' | sed '1{a X}'", '', "sed: -e expression #1, char 0: unmatched `{'\n", 1],
    ["printf 'a\\nb\\n' | sed '1c X'", "X\nb\n"],
    ["printf '1\\n2\\n3\\n' | sed '\$!c X'", "X\nX\n3\n"],
    ["printf '1\\n2\\n3\\n' | sed '1,/x/c X'", ''],
    ["printf '1\\n2\\n3\\n' | sed '2,1c X'", "1\nX\n3\n"],
    ["printf '1\\n2\\n3\\n' | sed '/1/,+1c X'", "X\n3\n"],
    ["printf '1\\n2\\n3\\n' | sed '1,2!c X'", "1\n2\nX\n"],
    ["printf '1\\n2\\n' | sed 'c\\\nA\\\nB'", "A\nB\nA\nB\n"],
    ["printf '1\\n2\\n' | sed -n 'c X'", "X\nX\n"],
    ["printf '1\\n2\\n' | sed 'i\\\nA\\\nB'", "A\nB\n1\nA\nB\n2\n"],
    ["printf 'a' | sed 'c X'", "X\n"],
    ["printf 'a\\nb' | sed '\$c X'", "a\nX\n"],
    ["printf 'a\\nb' | sed 'a X'", "a\nX\nb\nX\n"],
    ["echo 'hello' | sed 's/.*/\\U\\l&/'", "hELLO\n"],
    ["echo 'ab' | sed 's/\\(a\\)\\(b\\)/\\U\\1\\E\\2/'", "Ab\n"],
    ["echo 'ab' | sed -E 's/()(a)/\\u\\1\\2/'", "Ab\n"],
    ["echo 'ab' | sed -E 's/(x?)(a)/\\u\\1\\2/'", "Ab\n"],
    ["echo 'abc' | sed -E 's/(a)(b)/\\u\\1x\\2/'", "Axbc\n"],
    ["echo 'abc' | sed 's/b/\\ux/'", "aXc\n"],
    ["echo 'abc' | sed 's/b/\\uxy\\Uz/'", "aXyZc\n"],
    ["echo 'abc' | sed 's/abc/\\u\\U&/'", "ABC\n"],
    ["echo 'abc' | sed 's/abc/\\U\\u&x\\lYZ/'", "ABCXyZ\n"],
    ["echo 'Abc' | sed 's/abc/\\L&/I'", "abc\n"],
    ["echo 'abc' | sed 's/b/[&]\\&/'", "a[b]&c\n"],
    ["echo 'abc' | sed 's/b/\\q\\%/'", "aq%c\n"],
    ["echo 'abc' | sed 's&b&\\&&'", "a&c\n"],
    ["echo 'abc' | sed 's/b/a\\\\/'", "aa\\c\n"],
    ["echo 'abc' | sed 's/\\(b\\)/\\1\\1\\0/'", "abbbc\n"],
    ["echo 'abcb' | sed 's/b/x/;s//[\\1]/'", "axc[]\n"],
    ["echo 'abcb' | sed '/b/s//[\\1]/'", '', "sed: -e expression #1, char 0: invalid reference \\1 on `s' command's RHS\n", 1],
    ["printf '1\\n2\\n' | sed '/2/d;s//[\\1]/'", '', "sed: -e expression #1, char 0: invalid reference \\1 on `s' command's RHS\n", 1],
    ["printf 'b\\na\\n' | sed '/a/s//[\\1]/'", "b\n", "sed: -e expression #1, char 0: invalid reference \\1 on `s' command's RHS\n", 1],
    ["echo 'ab' | sed -E '/(a)/s//[\\1]/'", "[a]b\n"],
    ["echo 'ab' | sed 's/x/y/;s//z/I'", '', "sed: -e expression #1, char 13: cannot specify modifiers on empty regexp\n", 1],
    ["echo 'ab' | sed '//p'", '', "sed: -e expression #1, char 0: no previous regular expression\n", 1],
    ["echo 'ab' | sed '/b/d;1s/a/X/;s//Y/'", ''],
    ["printf 'a\\nb\\nc\\n' | sed '/b/d;1s/a/X/;s//Y/'", "X\nc\n"],
    ["echo 'ab' | sed 's/a/x/w'", '', "sed: -e expression #1, char 7: missing filename in r/R/w/W commands\n", 1],
    ["echo 'ab' | sed 's/a/x/ w out'; cat out", "xb\nxb\n"],
    ["echo 'ab' | sed 's/a/x/;#c\np'", "xb\nxb\n"],
    ["echo 'ab' | sed -n 's/a/x/p;p'", "xb\nxb\n"],
    ["echo 'ab' | sed 's/a/x/gg'", '', "sed: -e expression #1, char 8: multiple `g' options to `s' command\n", 1],
    ["echo 'ab' | sed 's/a/x/0'", '', "sed: -e expression #1, char 7: number option to `s' command may not be zero\n", 1],
    ["echo 'ab' | sed 's/a/x/1 2'", '', "sed: -e expression #1, char 9: multiple number options to `s' command\n", 1],
    ["echo 'ab' | sed 's/a/x/k'", '', "sed: -e expression #1, char 7: unknown option to `s'\n", 1],
    ["echo 'ab' | sed \$'s/a/x/\\rp'", '', "sed: -e expression #1, char 8: unknown option to `s'\n", 1],
    ["echo 'ab' | sed 's/a/x/m;s/b/y/M;s/x/Z/i'", "Zy\n"],
    ["echo 'ab' | sed 's/a/x/}'", '', "sed: -e expression #1, char 7: unexpected `}'\n", 1],
    ["echo 'ab' | sed '{s/a/x/}'", "xb\n"],
    ["sed -n '2,4p' n.txt", "2\n3\n4\n"],
    ["sed -n '2 , 4 p' n.txt", "2\n3\n4\n"],
    ["sed -n '\$p' n.txt", "15\n"],
    ["sed -n '13,\$p' n.txt", "13\n14\n15\n"],
    ["sed -n '/3/,/5/p' n.txt", "3\n4\n5\n13\n14\n15\n"],
    ["sed -n '/1/,/1/p' n.txt", "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '5,/./p' n.txt", "5\n6\n"],
    ["sed -n '0,/1/p' n.txt", "1\n"],
    ["sed -n '0,/3/p' n.txt", "1\n2\n3\n"],
    ["sed -n '0,5p' n.txt", '', "sed: -e expression #1, char 4: invalid usage of line address 0\n", 1],
    ["sed -n '0p' n.txt", '', "sed: -e expression #1, char 2: invalid usage of line address 0\n", 1],
    ["sed -n '0~4p' n.txt", "4\n8\n12\n"],
    ["sed -n '3~4p' n.txt", "3\n7\n11\n15\n"],
    ["sed -n '3 ~ 4p' n.txt", "3\n7\n11\n15\n"],
    ["sed -n '2~0p' n.txt", "2\n"],
    ["sed -n '0~0p' n.txt", '', "sed: -e expression #1, char 4: invalid usage of line address 0\n", 1],
    ["sed -n '2~p' n.txt", "2\n"],
    ["sed -n '/4/,+2p' n.txt", "4\n5\n6\n14\n15\n"],
    ["sed -n '/4/,~4p' n.txt", "4\n5\n6\n7\n8\n14\n15\n"],
    ["sed -n '4,~4p' n.txt", "4\n5\n6\n7\n8\n"],
    ["sed -n '/1/,+0p' n.txt", "1\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '/1/,~0p' n.txt", "1\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '\$,/x/p' n.txt", "15\n"],
    ["sed -n '/5/,3p' n.txt", "5\n15\n"],
    ["sed -n '5,3p' n.txt", "5\n"],
    ["sed -n '2,4!p' n.txt", "1\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '/1/!p' n.txt", "2\n3\n4\n5\n6\n7\n8\n9\n"],
    ["sed -n '2,4{n;p}' n.txt", "3\n5\n"],
    ["sed -n '3,5{N;p}' n.txt", "3\n4\n5\n6\n"],
    ["sed -n '/2/,/4/{N;N;p}' n.txt", "2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n"],
    ["sed '2,3N;s/\\n/+/' n.txt", "1\n2+3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '1~3,+1p' n.txt", "1\n2\n4\n5\n7\n8\n10\n11\n13\n14\n"],
    ["sed -n '\$!{\$!p}' b.txt", "one\ntwo\n"],
    ["sed -n '2,1~5p' n.txt", "2\n3\n4\n5\n6\n"],
    ["sed -n '9,1~5p' n.txt", "9\n10\n11\n"],
    ["sed -n '2,\$p' b.txt nope", "two\nthree\n", "sed: can't read nope: No such file or directory\n", 2],
    ["sed -n '\\,1,p' n.txt", "1\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '\\n1np' n.txt", "1\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '\\;1;p' n.txt", "1\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '/[/]/p' n.txt", ''],
    ["sed -n '/1\\/2/p' n.txt", ''],
    ["sed -n '\\%1\\%%p' n.txt", ''],
    ["sed -n '+1p' n.txt", '', "sed: -e expression #1, char 2: invalid usage of +N or ~N as first address\n", 1],
    ["sed -n '~1p' n.txt", '', "sed: -e expression #1, char 2: invalid usage of +N or ~N as first address\n", 1],
    ["sed -n '+0p' n.txt", "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed -n '1,p' n.txt", '', "sed: -e expression #1, char 3: unexpected `,'\n", 1],
    ["sed -n '1,xp' n.txt", '', "sed: -e expression #1, char 3: unexpected `,'\n", 1],
    ["sed -n '1!!p' n.txt", '', "sed: -e expression #1, char 3: multiple `!'s\n", 1],
    ["sed -n '1! !p' n.txt", '', "sed: -e expression #1, char 4: multiple `!'s\n", 1],
    ["sed -n '1 ! p' n.txt", "2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n"],
    ["sed '0,5d' n.txt", '', "sed: -e expression #1, char 4: invalid usage of line address 0\n", 1],
    ["sed '0,\$d' n.txt", '', "sed: -e expression #1, char 4: invalid usage of line address 0\n", 1],
    ["sed '0r b.txt' a.txt", "one\ntwo\nthree\nhello\nworld\n"],
    ["sed '0!r b.txt' a.txt", '', "sed: -e expression #1, char 2: invalid usage of line address 0\n", 1],
    ["sed '0,/l/r b.txt' a.txt", "hello\none\ntwo\nthree\nworld\n"],
    ["sed '1,2q' b.txt", '', "sed: -e expression #1, char 4: command only uses one address\n", 1],
    ["sed '1,2Q' b.txt", '', "sed: -e expression #1, char 4: command only uses one address\n", 1],
    ["sed '1,2=' b.txt", "1\none\n2\ntwo\nthree\n"],
    ["sed -n '/x' n.txt", '', "sed: -e expression #1, char 2: unterminated address regex\n", 1],
    ["sed -n '/x/' n.txt", '', "sed: -e expression #1, char 3: missing command\n", 1],
    ["sed -n '\\' n.txt", '', "sed: -e expression #1, char 1: unterminated address regex\n", 1],
    ["sed -n '\\x' n.txt", '', "sed: -e expression #1, char 2: unterminated address regex\n", 1],
    ["sed 'k' n.txt", '', "sed: -e expression #1, char 1: unknown command: `k'\n", 1],
    ["sed '1' n.txt", '', "sed: -e expression #1, char 1: missing command\n", 1],
    ["sed '1 ' n.txt", '', "sed: -e expression #1, char 2: missing command\n", 1],
    ["sed 'pq' n.txt", '', "sed: -e expression #1, char 2: extra characters after command\n", 1],
    ["sed 'p q' n.txt", '', "sed: -e expression #1, char 3: extra characters after command\n", 1],
    ["sed 'p;;;q' n.txt", "1\n1\n"],
    ["sed 'q;' n.txt", "1\n"],
    ["sed 'p # c' n.txt", "1\n1\n2\n2\n3\n3\n4\n4\n5\n5\n6\n6\n7\n7\n8\n8\n9\n9\n10\n10\n11\n11\n12\n12\n13\n13\n14\n14\n15\n15\n"],
    ["sed 'd}' n.txt", '', "sed: -e expression #1, char 2: unexpected `}'\n", 1],
    ["sed 'v'", ''],
    ["sed 'v 4.2' b.txt", "one\ntwo\nthree\n"],
    ["sed 'v4.9' b.txt", "one\ntwo\nthree\n"],
    ["sed 'v 4.10' b.txt", '', "sed: -e expression #1, char 6: expected newer version of sed\n", 1],
    ["sed 'v 5' b.txt", '', "sed: -e expression #1, char 3: expected newer version of sed\n", 1],
    ["sed 'v;p' b.txt", "one\none\ntwo\ntwo\nthree\nthree\n"],
    ["sed '1v' b.txt", "one\ntwo\nthree\n"],
    ["sed '#n' b.txt", ''],
    ["sed '#nfoo' b.txt", ''],
    ["sed ' #n' b.txt", "one\ntwo\nthree\n"],
    ["sed '#n\np' b.txt", "one\ntwo\nthree\n"],
    ["sed -e p -e '#n' b.txt", "one\none\ntwo\ntwo\nthree\nthree\n"],
    ["sed '#x\n#n\np' b.txt", "one\none\ntwo\ntwo\nthree\nthree\n"],
    ["sed 's/\\(/x/' b.txt", '', "sed: -e expression #1, char 7: Unmatched ( or \\(\n", 1],
    ["sed 's/a\\)/x/' b.txt", '', "sed: -e expression #1, char 8: Unmatched ) or \\)\n", 1],
    ["sed -E 's/(a/x/' b.txt", '', "sed: -e expression #1, char 7: Unmatched ( or \\(\n", 1],
    ["sed 's/[/x/' b.txt", '', "sed: -e expression #1, char 6: unterminated `s' command\n", 1],
    ["sed 's/[[:alpha:]/x/' b.txt", '', "sed: -e expression #1, char 15: unterminated `s' command\n", 1],
    ["sed 's/[[:alpha/x/' b.txt", '', "sed: -e expression #1, char 13: unterminated `s' command\n", 1],
    ["sed 's/a\\{1/x/' b.txt", '', "sed: -e expression #1, char 9: Unmatched \\{\n", 1],
    ["sed 's/a\\{x\\}/x/' b.txt", '', "sed: -e expression #1, char 11: Invalid content of \\{\\}\n", 1],
    ["sed 's/\\x5c/X/' b.txt", '', "sed: -e expression #1, char 9: Trailing backslash\n", 1],
    ["sed 's/a**/X/' b.txt", '', "sed: -e expression #1, char 8: Invalid preceding regular expression\n", 1],
    ["sed -E 's/a**/X/' b.txt", "Xone\nXtwo\nXthree\n"],
    ["sed -E 's/a+*/X/' b.txt", "Xone\nXtwo\nXthree\n"],
    ["sed -E 's/(*a)/X/' b.txt", '', "sed: -e expression #1, char 9: Invalid preceding regular expression\n", 1],
    ["sed -E 's/a|*b/X/' b.txt", '', "sed: -e expression #1, char 9: Invalid preceding regular expression\n", 1],
    ["sed -E 's/^*a/X/' b.txt", '', "sed: -e expression #1, char 8: Invalid preceding regular expression\n", 1],
    ["sed 's/^*a/X/' b.txt", "one\ntwo\nthree\n"],
    ["sed 's/\\(^a\\)/X/' b.txt", "one\ntwo\nthree\n"],
    ["sed 's/a\\|^b/X/' b.txt", "one\ntwo\nthree\n"],
    ["sed 's/[]/x/' b.txt", '', "sed: -e expression #1, char 7: unterminated `s' command\n", 1],
    ["sed 's/[^]]/x/' b.txt", "xne\nxwo\nxhree\n"],
    ["sed 's/\\n/x/' b.txt", "one\ntwo\nthree\n"],
    ["sed 'y/a\\n/xy/' b.txt", "one\ntwo\nthree\n"],
    ["sed 'y/\\x/y/' b.txt", "one\ntwo\nthree\n"],
    ["echo 'a b' | sed 's/\\>/X/g'", "aX bX\n"],
    ["echo 'a b' | sed 's/\\</X/g'", "Xa Xb\n"],
    ["echo 'a b' | sed 's/\\b/X/g'", "XaX XbX\n"],
    ["echo 'a b' | sed 's/\\B/X/g'", "a b\n"],
    ["echo 'ab cd' | sed 's/\\<./X/g;s/.\\>/Y/g'", "XY XY\n"],
    ["echo aaa | sed 's/a**/X/'", '', "sed: -e expression #1, char 8: Invalid preceding regular expression\n", 1],
    ["echo aaa | sed -E 's/a**/X/'", "X\n"],
    ["echo aaa | sed -E 's/a+*/X/'", "X\n"],
    ["echo aaa | sed -E 's/a*?/X/'", "X\n"],
    ["echo aaa | sed -E 's/a*+/X/'", "X\n"],
    ["echo aaa | sed -E 's/a{1}{2}/X/'", "Xa\n"],
    ["echo aaa | sed 's/a*\\{2\\}/X/'", '', "sed: -e expression #1, char 12: Invalid preceding regular expression\n", 1],
    ["echo aaa | sed -E 's/(a)*{2}/X/'", "X\n"],
    ["echo 'aaa' | sed -E 's/a{,2}/X/'", "Xa\n"],
    ["echo 'aaa' | sed -E 's/a{,}/X/'", "X\n"],
    ["echo 'aaa' | sed -E 's/a{}/X/'", '', "sed: -e expression #1, char 8: Invalid content of \\{\\}\n", 1],
    ["echo 'aaa' | sed -E 's/a{1,2,3}/X/'", '', "sed: -e expression #1, char 13: Invalid content of \\{\\}\n", 1],
    ["echo 'aaa' | sed -E 's/a{1,x}/X/'", '', "sed: -e expression #1, char 11: Invalid content of \\{\\}\n", 1],
    ["echo 'aaa' | sed -E 's/a{x,1}/X/'", '', "sed: -e expression #1, char 11: Invalid content of \\{\\}\n", 1],
    ["echo 'aaa' | sed -E 's/a{1,/X/'", '', "sed: -e expression #1, char 9: Unmatched \\{\n", 1],
    ["echo 'aaa' | sed -E 's/a{40000}/X/'", '', "sed: -e expression #1, char 13: Regular expression too big\n", 1],
    ["echo 'aaa' | sed -E 's/a{2,1}/X/'", '', "sed: -e expression #1, char 11: Invalid content of \\{\\}\n", 1],
    ["echo 'a{' | sed -E 's/a{/X/'", '', "sed: -e expression #1, char 7: Unmatched \\{\n", 1],
    ["echo 'a{1' | sed -E 's/a{1/X/'", '', "sed: -e expression #1, char 8: Unmatched \\{\n", 1],
    ["echo 'a{' | sed 's/a\\{/X/'", '', "sed: -e expression #1, char 8: Unmatched \\{\n", 1],
    ["echo 'a{x}' | sed -E 's/a{x}/X/'", '', "sed: -e expression #1, char 9: Invalid content of \\{\\}\n", 1],
    ["echo 'a{x}' | sed 's/a\\{x\\}/X/'", '', "sed: -e expression #1, char 11: Invalid content of \\{\\}\n", 1],
    ["echo 'a{1}' | sed 's/a{1}/X/'", "X\n"],
    ["echo 'a}' | sed -E 's/a}/X/'", "X\n"],
    ["echo 'a}' | sed 's/a\\}/X/'", "X\n"],
    ["echo '{a' | sed -E 's/{a/X/'", '', "sed: -e expression #1, char 7: Invalid preceding regular expression\n", 1],
    ["echo '{a' | sed 's/\\{a/X/'", '', "sed: -e expression #1, char 8: Invalid preceding regular expression\n", 1],
    ["echo '+a' | sed 's/\\+a/X/'", "X\n"],
    ["echo '?a' | sed 's/\\(\\?a\\)/X/'", "X\n"],
    ["echo 'a' | sed -E 's/(+a)/X/'", '', "sed: -e expression #1, char 9: Invalid preceding regular expression\n", 1],
    ["echo 'a' | sed -E 's/a|?b/X/'", '', "sed: -e expression #1, char 9: Invalid preceding regular expression\n", 1],
    ["echo '*a' | sed 's/\\(*a\\)/X/'", "X\n"],
    ["echo '*a' | sed 's/x\\|*a/X/'", "X\n"],
    ["echo 'a' | sed -E 's/^*a/X/'", '', "sed: -e expression #1, char 8: Invalid preceding regular expression\n", 1],
    ["echo '^*a' | sed 's/^*a/X/'", "^*a\n"],
    ["echo 'a^b' | sed -E 's/a^b/X/'", "a^b\n"],
    ["echo 'a\$b' | sed -E 's/a\$b/X/'", "a\$b\n"],
    ["echo 'a\$b' | sed 's/a\$b/X/'", "X\n"],
    ["echo 'ab' | sed 's/\\(a\\)\\(b\\)\\{2\\}/X/'", "ab\n"],
    ["echo 'abab' | sed -E 's/(ab){2}/X/'", "X\n"],
    ["echo 'a.b' | sed 's/a\\.b/X/'", "X\n"],
    ["echo 'a(b' | sed -E 's/a\\(b/X/'", "X\n"],
    ["echo 'a|b' | sed -E 's/a\\|b/X/'", "X\n"],
    ["echo 'a' | sed 's/a\\/X/'", '', "sed: -e expression #1, char 7: unterminated `s' command\n", 1],
    ["echo 'a' | sed -E 's/a)/X/'", '', "sed: -e expression #1, char 7: Unmatched ) or \\)\n", 1],
    ["echo 'a' | sed 's/a\\)/X/'", '', "sed: -e expression #1, char 8: Unmatched ) or \\)\n", 1],
    ["echo 'ab' | sed -E 's/(a)(b)\\3/X/'", '', "sed: -e expression #1, char 13: Invalid back reference\n", 1],
    ["echo 'abb' | sed -E 's/a(b)\\1/X/'", "X\n"],
    ["echo 'a' | sed 's/[[:upper:]]*/X/'", "Xa\n"],
    ["echo 'A1 b' | sed 's/[[:upper:][:digit:]]/X/g'", "XX b\n"],
    ["echo 'a1 b' | sed 's/[^[:alnum:]]/X/g'", "a1Xb\n"],
    ["echo 'a-z' | sed 's/[a\\-z]/X/g'", "X-X\n"],
    ["echo 'a]b' | sed 's/[]a]/X/g'", "XXb\n"],
    ["echo 'a]b' | sed 's/[^]a]/X/g'", "a]X\n"],
    ["echo 'a-b' | sed 's/[a-]/X/g'", "XXb\n"],
    ["echo 'a.b' | sed 's/[.]/X/g'", "aXb\n"],
    ["echo 'a|b' | sed -E 's/[|]/X/g'", "aXb\n"],
    ["echo 'a[b' | sed 's/[[]/X/g'", "aXb\n"],
    ["echo 'a:b' | sed 's/[[:]/X/g'", '', "sed: -e expression #1, char 10: unterminated `s' command\n", 1],
    ["echo 'a b' | sed 's/[[:space:]]/X/g;s/[[:blank:]]/Y/'", "aXb\n"],
    ["echo 'a b' | sed 's/[[:punct:][:cntrl:][:graph:][:print:][:xdigit:][:lower:]]/X/g'", "XXX\n"],
    ["echo 'aB' | sed 's/[a-z]/X/Ig'", "XX\n"],
    ["echo 'a' | sed 's/[[:foo:]]/X/'", '', "sed: -e expression #1, char 14: Invalid character class name\n", 1],
    ["echo 'a' | sed 's/[[=a=]b]/X/'", "X\n"],
    ["echo 'a' | sed 's/[[.a.]-c]/X/'", "X\n"],
    ["echo 'b' | sed 's/[a-[.c.]]/X/'", "X\n"],
    ["echo 'a' | sed 's/[[.a/X/'", '', "sed: -e expression #1, char 9: unterminated `s' command\n", 1],
    ["echo 'a' | sed 's/[z-a]/X/'", '', "sed: -e expression #1, char 10: Invalid range end\n", 1],
    ["echo 'tab\tx' | sed 's/\\t/T/'", "tabTx\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/a\\nb/X/'", "X\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/.*/[&]/'", "[a\nb]\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/.*/[&]/M'", "[a]\nb\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/^.*\$/[&]/Mg'", "[a]\n[b]\n"],
    ["printf 'ab\\ncd\\n' | sed 'N;s/[^a]*/X/M'", "Xab\ncd\n"],
    ["printf 'a\\n' | sed 'G;G;s/\\n\$/E/'", "a\nE\n"],
    ["printf 'a\\n' | sed 'G;s/\$/E/g'", "a\nE\n"],
    ["printf 'a\\n' | sed 'G;s/^/S/Mg'", "Sa\nS\n"],
    ["printf 'a\\n' | sed 'G;s/\$/E/Mg'", "aE\nE\n"],
    ["echo 'aaa' | sed 's/a/b/3g'", "aab\n"],
    ["echo 'hello' | sed 's/\\(l\\)\\(o\\)*/[\\1\\2]/g'", "he[l][lo]\n"],
    ["echo 'abc' | sed -E 's/(x)?b/[\\1]/'", "a[]c\n"],
    ["echo 'abc' | sed -E 's/(b)|(c)/[\\1\\2]/g'", "a[b][c]\n"],
    ["echo ab | sed \"\$(printf 's/a/x/\\r')\"", '', "sed: -e expression #1, char 7: unknown option to `s'\n", 1],
    ["echo ab | sed \"\$(printf 's/a/x/\\rp')\"", '', "sed: -e expression #1, char 8: unknown option to `s'\n", 1],
    ["echo ab | sed \"\$(printf 'p\\r')\"", '', "sed: -e expression #1, char 2: extra characters after command\n", 1],
    ["echo x | sed 'a\n'", "x\n\n"],
    ["echo x | sed 'a\nfoo'", '', "sed: -e expression #1, char 3: unknown command: `f'\n", 1],
    ["sed '1\np' n.txt", '', "sed: -e expression #1, char 2: unknown command: `\n'\n", 1],
    ["sed -n '/[[:digit:]]\\{2\\}/{s/1/one/;p}' n.txt", "one0\none1\none2\none3\none4\none5\n"],
    ["sed '1#foo' b.txt", '', "sed: -e expression #1, char 2: comments don't accept any addresses\n", 1],
    ["printf 's/o/0/\\r\\np\\n' > script; sed -f script b.txt", "0ne\n0ne\ntw0\ntw0\nthree\nthree\n"],
    ["sed 's/a\\' b.txt", '', "sed: -e expression #1, char 4: unterminated `s' command\n", 1],
    ["sed '/a\\' b.txt", '', "sed: -e expression #1, char 3: unterminated address regex\n", 1],
    ["printf 'a\\nb\\0c\\0' | sed -z 's/^b/X/M' | tr '\\000' @", "a\nb@c@"],
    ["printf 'a\\nb\\0c\\0' | sed -z 'N;s/^c/X/M;s/b\$/Y/M' | tr '\\000' @", "a\nY@X@"],
    ["printf 'ab\\0cd\\0' | sed -z 'N;s/b.c/X/M;s/a[^x]*/<&>/M' | tr '\\000' @", '<ab>@cd@'],
    ["printf 'ab\\0cd\\0' | sed -z 'N;s/b.c/X/' | tr '\\000' @", 'aXd@'],
    ["printf 'ab\\0cd\\0' | sed -z 'N;s/^/>/Mg;s/\$/</Mg' | tr '\\000' @", '>ab<@>cd<@'],
    ["printf 'ab\\0cd\\0' | sed -z 'N;s/\\`/>/Mg;s/'\"\\\\\\\\'\"'/</Mg' | tr '\\000' @", '>ab@>cd@'],
    ["printf 'ab\\ncd\\n' | sed 'N;s/\\`/>/Mg;s/'\"\\\\\\\\'\"'/</Mg'", ">ab\ncd\n"],
    ["printf 'a.b\\n' | sed 's/./X/2M'", "aXb\n"],
    ["printf 'a\\nb\\n' | sed 'N;s/a.b/X/M'", "a\nb\n"],
]);

test('sed keeps a missing final newline like GNU sed', $sed)->with([
    ["printf 'a\\nb' | sed x", "\na\n"],
    ["printf 'a\\nb' | sed -n 'H;\${x;p}'", "\na\nb"],
    ["printf 'a\\nb' | sed '1h;\$g'", "a\na\n"],
    ["printf 'a\\nb' | sed '\$!d;G'", "b\n\n"],
    ["printf 'a\\nb' | sed 'h;\$!d;x'", 'b'],
    ["printf 'a\\nb' | sed -n '\$!{h;d};x;G;p'", "a\nb"],
    ["printf 'a\\nb' | sed 'N;P;D'", "a\nb"],
    ["printf 'a\\nb' | sed '\$!N;s/\\n/-/'", 'a-b'],
    ["printf 'a\\nb' | sed 'n;s/b/c/'", "a\nc"],
    ["printf 'a\\nb' | sed -n 'n;p'", 'b'],
    ["printf 'a\\nb' | sed '\$s/b/echo X/e'", "a\nX"],
    ["printf 'a\\nb' | sed '\$e echo X'", "a\nX\nb"],
    ["printf 'echo X' | sed 's/X/Y/;e'", 'Y'],
    ["printf 'echo X' | sed 's/^echo //;s/^/echo /;e'", 'X'],
    ["printf 'a\\nb' | sed 'w /dev/stdout'", "a\na\nbb"],
    ["printf 'a\\nb' | sed -n 'p;w /dev/stdout'", "a\na\nbb"],
    ["printf 'a\\nb' | sed 'p' partial -", "no newline\nno newline\na\na\nb\nb"],
    ["printf 'a\\nb' | sed -s 'p' partial -", "no newline\nno newline\na\na\nb\nb"],
    ["printf 'a' | sed -n 'p;p'", "a\na"],
    ["printf 'a' | sed 'a X' partial", "no newline\nX\n"],
    ["printf 'a' | sed '\$r partial'", "a\nno newline"],
    ["printf 'a' | sed 'R partial'", "a\nno newline"],
    ["printf 'a' | sed 'R partial' partial", "no newline\nno newline"],
    ["printf 'a' | sed '1r partial' - partial", "a\nno newlineno newline"],
    ["printf 'a' | sed 'l'", "a\$\na"],
    ["printf 'a' | sed '='", "1\na"],
    ["printf 'a' | sed 'F'", "-\na"],
    ["printf 'a' | sed -n 'p;l'", "a\na\$\n"],
    ["printf 'a' | sed 'p;i X'", "a\nX\na"],
    ["printf 'a' | sed 'e echo X'", "X\na"],
    ["printf 'a' | sed 'p;e echo X'", "a\nX\na"],
    ["printf 'a' | sed '0r partial'", 'no newlinea'],
    ["printf 'a\\nb\\n' | sed '0r partial'", "no newlinea\nb\n"],
    ["printf 'a\\nb\\n' | sed 'p;0r partial'", "a\nno newlinea\nb\nb\n"],
    ["printf '1\\n2\\n3\\n' | sed 'a X' | sed -n 'N;N;P;D'", "1\nX\n"],
    ["printf '1\\n2\\n3\\n' | sed '1{N;a X' -e 'D}'", '', "sed: -e expression #1, char 2: unexpected `}'\n", 1],
    ["printf '1\\n2\\n3\\n' | sed 'a X' -e '\$!N;P;D'", '', "sed: can't read a X: No such file or directory\n", 2],
    ["printf '1\\n2\\n3\\n' | sed -n '\$!N;l;D'", "1\\n2\$\n2\\n3\$\n3\$\n"],
    ["printf '1\\n2\\n3\\n' | sed 'N;N;s/\\n/+/;D'", "3\n"],
    ["printf '1\\n2\\n3\\n' | sed '2{x;p;x}'", "1\n\n2\n3\n"],
    ["printf '1\\n2\\n3\\n' | sed -n '2{c X' -e '};p'", '', "sed: -e expression #1, char 1: unexpected `}'\n", 1],
    ["printf '1\\n2\\n3\\n' | sed '2{i\\' -e 'X' -e '}'", '', "sed: -e expression #1, char 1: unknown command: `X'\n", 1],
    ["printf '1\\n2\\n3\\n' | sed -n '/2/,/3/{=;l}'", "2\n2\$\n3\n3\$\n"],
    ["printf '1\\n2\\n3\\n' | sed 'G;G'", "1\n\n\n2\n\n\n3\n\n\n"],
    ["printf '1\\n2\\n3\\n' | sed 'x;G;1d'", "1\n2\n2\n3\n"],
    ["printf '1\\n2\\n3\\n' | sed '\$!{N};P;D'", "1\n2\n3\n"],
    ["printf 'a b c\\n' | sed 's/ /\\n/g' | sed -n '2p'", "b\n"],
    ["printf 'hello\\n' | sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'", "HELLO\n"],
    ["printf 'one two\\n' | sed -E 's/(\\w+) (\\w+)/\\2 \\1/'", "two one\n"],
    ["printf 'path/to/file\\n' | sed 's|/|\\\\|g'", "path\\to\\file\n"],
    ["printf 'a,b,c\\n' | sed 's/,/\\n/2'", "a,b\nc\n"],
    ["printf 'key=value\\n' | sed 's/=.*//'", "key\n"],
    ["printf '  x  \\n' | sed 's/^[ \\t]*//;s/[ \\t]*\$//'", "x\n"],
    ["printf 'abc\\n' | sed 's/./&\\n/g' | sed '/^\$/d'", "a\nb\nc\n"],
    ["printf '<b>x</b>\\n' | sed 's/<[^>]*>//g'", "x\n"],
    ["printf 'x\\n' | sed -n '/x/{p;p;q}'", "x\nx\n"],
    ["printf 'x\\ny\\n' | sed '\$!s/\$/,/'", "x,\ny\n"],
    ["printf 'x\\ny\\n' | sed -e '\$a\\' -e 'END'", "x\ny\nEND\n"],
    ["printf 'x\\ny\\n' | sed '1i\\\\tTAB'", "\tTAB\nx\ny\n"],
    ["printf '#!/bin/sh\\necho\\n' | sed '1!b;s/sh/bash/'", "#!/bin/bash\necho\n"],
    ["printf 'x\\n' | sed 's/x/\\\n/'", "\n\n"],
    ["printf 'a\\n' | sed 's/a/b/;:x;s/b/c/;tx'", "c\n"],
    ["printf 'aaa\\n' | sed ':x;s/a/b/;tx'", "bbb\n"],
    ["printf 'aXbXc\\n' | sed 's/X/\\n/;P;D'", "a\nb\nc\n"],
    ["printf 'CamelCaseWord\\n' | sed -E 's/([A-Z])/_\\l\\1/g;s/^_//'", "camel_case_word\n"],
    ["printf 'snake_case_word\\n' | sed -E 's/_(.)/\\u\\1/g'", "snakeCaseWord\n"],
    ["printf 'x\\n' | sed --expression='s/x/y/' --quiet --expression p", "y\n"],
    ["printf 'x\\n' | sed -n -e 'p' -s -E -u -z", "x\n"],
]);

test('sed reports bad options with the usage text', function (string $script, string $message): void {
    $result = $this->bash->exec($script);

    expect($result->stdout)->toBe('')
        ->and($result->stderr)->toBe($message.SED_USAGE)
        ->and($result->exitCode)->toBe(1);
})->with([
    // glibc's getopt wording
    ['sed --s p b.txt', "sed: option '--s' is ambiguous; possibilities: '--silent' '--sandbox' '--separate'\n"],
    ['sed --quiet=x p b.txt', "sed: option '--quiet' doesn't allow an argument\n"],
    ['sed --expression', "sed: option '--expression' requires an argument\n"],
    ['sed --foo', "sed: unrecognized option '--foo'\n"],
    ['sed -k p b.txt', "sed: invalid option -- 'k'\n"],
    ['sed -nk p', "sed: invalid option -- 'k'\n"],
    ['sed -l', "sed: option requires an argument -- 'l'\n"],
    ['sed -e', "sed: option requires an argument -- 'e'\n"],
    ['sed', ''],
]);

test('sed --help prints the usage text', function (): void {
    expect($this->bash->exec('sed --help')->stdout)->toBe(SED_USAGE."E-mail bug reports to: <bug-sed@gnu.org>.\n");
});

test('e runs its command in the sandboxed shell', function (): void {
    // GNU sed runs /bin/sh, which words the error its own way
    $result = $this->bash->exec("echo 'x' | sed 'e'");

    expect($result->stdout)->toBe("\n")
        ->and($result->stderr)->toBe("bash: x: command not found\n")
        ->and($result->exitCode)->toBe(0);
});

test('sed stops scripts that loop without reading input', function (string $script, string $message): void {
    $bash = new Bash(new BashOptions(limits: new Limits(maxOutputSize: 1000, maxStringLength: 1000, maxSedIterations: 50)));

    expect(fn (): \BashBox\BashExecResult => $bash->exec($script))->toThrow(ExecutionLimitException::class, $message);
})->with([
    'branch loop' => ["echo x | sed ':a;ba'", 'sed: iteration limit exceeded'],
    't loop' => ["echo x | sed ':a;s/x/x/;ta'", 'sed: iteration limit exceeded'],
    'T loop' => ["echo x | sed ':a;s/y/y/;Ta'", 'sed: iteration limit exceeded'],
    'D loop' => ["echo x | sed 'G;D'", 'sed: iteration limit exceeded'],
    'growing pattern space' => ["echo x | sed ':a;s/.*/&&/;ta'", 'sed: buffer size limit exceeded'],
    'growing output' => ["seq -s, 30 | sed ':a;p;ba'", 'sed: buffer size limit exceeded'],
]);

test('sed reads long input without hitting the iteration limit', function (): void {
    $bash = new Bash(new BashOptions(limits: new Limits(maxSedIterations: 5)));

    expect($bash->exec("seq 20 | sed ':a;N;\$!ba;s/\\n/,/g'")->stdout)->toBe(implode(',', range(1, 20))."\n");
});
