<?php

declare(strict_types=1);

use BashBox\Bash;

// Every expected output below was checked against GNU bash 5.3 (`bash -c '<script>'`).

test('shopt', function (string $script, string $stdout, string $stderr = '', int $exitCode = 0): void {
    $bashExecResult = (new Bash)->exec($script);

    expect([$bashExecResult->stdout, $bashExecResult->stderr, $bashExecResult->exitCode])->toBe([$stdout, $stderr, $exitCode]);
})->with([
    'shopt lists every option' => ['shopt', "array_expand_once   \toff\nassoc_expand_once   \toff\nautocd              \toff\nbash_source_fullpath\toff\ncdable_vars         \toff\ncdspell             \toff\ncheckhash           \toff\ncheckjobs           \toff\ncheckwinsize        \ton\ncmdhist             \ton\ncompat31            \toff\ncompat32            \toff\ncompat40            \toff\ncompat41            \toff\ncompat42            \toff\ncompat43            \toff\ncompat44            \toff\ncomplete_fullquote  \ton\ndirexpand           \toff\ndirspell            \toff\ndotglob             \toff\nexecfail            \toff\nexpand_aliases      \toff\nextdebug            \toff\nextglob             \toff\nextquote            \ton\nfailglob            \toff\nforce_fignore       \ton\nglobasciiranges     \ton\nglobskipdots        \ton\nglobstar            \toff\ngnu_errfmt          \toff\nhistappend          \toff\nhistreedit          \toff\nhistverify          \toff\nhostcomplete        \ton\nhuponexit           \toff\ninherit_errexit     \toff\ninteractive_comments\ton\nlastpipe            \toff\nlithist             \toff\nlocalvar_inherit    \toff\nlocalvar_unset      \toff\nlogin_shell         \toff\nmailwarn            \toff\nno_empty_cmd_completion\toff\nnocaseglob          \toff\nnocasematch         \toff\nnoexpand_translation\toff\nnullglob            \toff\npatsub_replacement  \ton\nprogcomp            \ton\nprogcomp_alias      \toff\npromptvars          \ton\nrestricted_shell    \toff\nshift_verbose       \toff\nsourcepath          \ton\nvarredir_close      \toff\nxpg_echo            \toff\n"],
    'shopt -p prints them as commands' => ['shopt -p', "shopt -u array_expand_once\nshopt -u assoc_expand_once\nshopt -u autocd\nshopt -u bash_source_fullpath\nshopt -u cdable_vars\nshopt -u cdspell\nshopt -u checkhash\nshopt -u checkjobs\nshopt -s checkwinsize\nshopt -s cmdhist\nshopt -u compat31\nshopt -u compat32\nshopt -u compat40\nshopt -u compat41\nshopt -u compat42\nshopt -u compat43\nshopt -u compat44\nshopt -s complete_fullquote\nshopt -u direxpand\nshopt -u dirspell\nshopt -u dotglob\nshopt -u execfail\nshopt -u expand_aliases\nshopt -u extdebug\nshopt -u extglob\nshopt -s extquote\nshopt -u failglob\nshopt -s force_fignore\nshopt -s globasciiranges\nshopt -s globskipdots\nshopt -u globstar\nshopt -u gnu_errfmt\nshopt -u histappend\nshopt -u histreedit\nshopt -u histverify\nshopt -s hostcomplete\nshopt -u huponexit\nshopt -u inherit_errexit\nshopt -s interactive_comments\nshopt -u lastpipe\nshopt -u lithist\nshopt -u localvar_inherit\nshopt -u localvar_unset\nshopt -u login_shell\nshopt -u mailwarn\nshopt -u no_empty_cmd_completion\nshopt -u nocaseglob\nshopt -u nocasematch\nshopt -u noexpand_translation\nshopt -u nullglob\nshopt -s patsub_replacement\nshopt -s progcomp\nshopt -u progcomp_alias\nshopt -s promptvars\nshopt -u restricted_shell\nshopt -u shift_verbose\nshopt -s sourcepath\nshopt -u varredir_close\nshopt -u xpg_echo\n"],
    'shopt -s and -u list the ones on and off' => ['shopt -s; shopt -u | head -3; shopt -ps | head -2', "checkwinsize        \ton\ncmdhist             \ton\ncomplete_fullquote  \ton\nextquote            \ton\nforce_fignore       \ton\nglobasciiranges     \ton\nglobskipdots        \ton\nhostcomplete        \ton\ninteractive_comments\ton\npatsub_replacement  \ton\nprogcomp            \ton\npromptvars          \ton\nsourcepath          \ton\narray_expand_once   \toff\nassoc_expand_once   \toff\nautocd              \toff\nshopt -s checkwinsize\nshopt -s cmdhist\n"],
    'querying names fails when one is off' => ['shopt extglob; echo s=$?; shopt -p extglob; echo s=$?; shopt -s extglob; shopt extglob nullglob; echo s=$?; shopt -q nullglob extglob; echo q=$?; shopt -sq; echo s=$?; shopt -qs extglob; shopt -pq extglob; echo s=$?', "extglob             \toff\ns=1\nshopt -u extglob\ns=1\nextglob             \ton\nnullglob            \toff\ns=1\nq=1\ns=0\ns=0\n"],
    'unknown names are reported but the rest still apply' => ['shopt -s extglob nope nullglob; echo s=$?; shopt -p nullglob extglob; shopt -q nope; echo s=$?', "s=1\nshopt -s nullglob\nshopt -s extglob\ns=1\n", "bash: shopt: nope: invalid shell option name\nbash: shopt: nope: invalid shell option name\n"],
    '-- ends the flags' => ['shopt -- extglob; shopt -s -- dotglob; shopt -p dotglob', "extglob             \toff\nshopt -s dotglob\n"],
    'bad flags' => ['shopt -s -u x; echo s=$?; shopt -x; echo s=$?; shopt -sx; echo s=$?', "s=1\ns=2\ns=2\n", "bash: shopt: cannot set and unset shell options simultaneously\nbash: shopt: -x: invalid option\nshopt: usage: shopt [-pqsu] [-o] [optname ...]\nbash: shopt: -x: invalid option\nshopt: usage: shopt [-pqsu] [-o] [optname ...]\n"],
    '-o works on set -o options' => ['shopt -po; shopt -o; shopt -so; shopt -uo | head -2; shopt -o errexit; echo s=$?; shopt -qo errexit; echo s=$?', "set +o allexport\nset -o braceexpand\nset +o emacs\nset +o errexit\nset +o errtrace\nset +o functrace\nset -o hashall\nset +o histexpand\nset +o history\nset +o ignoreeof\nset -o interactive-comments\nset +o keyword\nset +o monitor\nset +o noclobber\nset +o noexec\nset +o noglob\nset +o nolog\nset +o notify\nset +o nounset\nset +o onecmd\nset +o physical\nset +o pipefail\nset +o posix\nset +o privileged\nset +o verbose\nset +o vi\nset +o xtrace\nallexport      \toff\nbraceexpand    \ton\nemacs          \toff\nerrexit        \toff\nerrtrace       \toff\nfunctrace      \toff\nhashall        \ton\nhistexpand     \toff\nhistory        \toff\nignoreeof      \toff\ninteractive-comments\ton\nkeyword        \toff\nmonitor        \toff\nnoclobber      \toff\nnoexec         \toff\nnoglob         \toff\nnolog          \toff\nnotify         \toff\nnounset        \toff\nonecmd         \toff\nphysical       \toff\npipefail       \toff\nposix          \toff\nprivileged     \toff\nverbose        \toff\nvi             \toff\nxtrace         \toff\nbraceexpand    \ton\nhashall        \ton\ninteractive-comments\ton\nallexport      \toff\nemacs          \toff\nerrexit             \toff\ns=1\ns=1\n"],
    '-o sets and unsets set -o options' => ['shopt -so pipefail; echo $?; shopt -o pipefail; false | true; echo $?; shopt -uo pipefail; false | true; echo $?; shopt -so errexit; echo $-; shopt -uo errexit; echo $-', "0\npipefail            \ton\n1\n0\nehBc\nhBc\n"],
    '-o with a bad name' => ['shopt -so nope; echo s=$?; shopt -uo nope; echo s=$?; shopt -o nope; echo s=$?; shopt -po nope errexit; echo s=$?', "s=0\ns=0\ns=1\nset +o errexit\ns=1\n", "bash: shopt: nope: invalid option name\nbash: shopt: nope: invalid option name\nbash: shopt: nope: invalid option name\nbash: shopt: nope: invalid option name\n"],
    'lastpipe is accepted' => ['shopt -s lastpipe; echo a | read v; echo "[$v]"', "[a]\n"],
    'aliases expand only with expand_aliases, from the next line on' => ["alias e='echo hi'\ne there\nshopt -s expand_aliases\ne there\nalias echo='echo [e]'; echo x; x=1 e y > f; cat f\nalias c='cat'; c <<EOF\nbody\nEOF\n\"e\" quoted; \\e back\nalias p='echo a | tr a b'; p\nunalias echo; e z\nalias echo='echo [e]'\ne w; echo v; alias q=echo; eval q ev\nf() { e inf; }; f", "hi there\nx\nhi y\n[e] hi z\n[e] hi w\n[e] v\n[e] ev\n[e] hi inf\n", "bash: e: command not found\nbash: c: command not found\nbash: e: command not found\nbash: e: command not found\nbash: p: command not found\n"],
]);
